---
version: 2.1

parameters:
    run_workflow_deploy:
        type: boolean
        default: true

## Start of build control of O58 and O562 plugins
## run_workflow_deploy_O58
##    type: boolean
##    default: true
## run_workflow_deploy_O562
##    type: boolean
##    default: false

std-filters: &std-filters
    filters:
        branches:
            ignore:
            - devel
            - tmp
        tags:
            only: /.*/

workflows:
    build_all:
        jobs:
###  --------------------
## OpenCPN 5.8 Plugins
## ----------------------
#        - build-android-arm64:
#             <<: *std-filters
#        - build-android-armhf:
#             <<: *std-filters
#        - build-macos-wx32:
#             <<: *std-filters
#        - build-flatpak-arm64-2208:
#           <<: *std-filters
#        - build-flatpak-x86-2208:
#            <<: *std-filters
## flatpak-armhf has Insufficient performance.
## Appveyor can also build for Windows.
#        - build-msvc-wx32-2022:
#            <<: *std-filters
#        - build-debian-arm64-12-bookworm:
#            <<: *std-filters
#        - build-debian-armhf-12-bookworm:
#           <<: *std-filters
#        - build-debian-x86_64-12-bookworm:
#            <<: *std-filters
## KEEP needed for Raspbian OpenCPN v5.8(wx32)
#        - build-ubuntu-x86_64-2204-jammy:
#            <<: *std-filters
## ---------------------
## OpenCPN 5.6.2 Plugins
## ---------------------
## Frozen - 28/05/2023
#        - build-macos:
#             <<: *std-filters
## Appveyor also builds for Windows.
## Frozen - 28/05/2023
        - build-msvc-2022:
            <<: *std-filters
## Frozen - 28/05/2023
#        - build-debian-armhf-10-buster:
#            <<: *std-filters
## Frozen - 28/05/2023
#        - build-debian-armhf-10-buster-gtk3:
#            <<: *std-filters
## Frozen - 28/05/2023
#       - build-debian-arm64-10-buster:
#            <<: *std-filters
## Frozen - 28/05/2023
#        - build-debian-x86_64-10-buster:
#            <<: *std-filters
## Frozen - 28/05/2023
#        - build-debian-armhf-11-bullseye:
#            <<: *std-filters
## Frozen - 28/05/2023
#        - build-debian-arm64-11-bullseye:
#            <<: *std-filters
## Frozen - 28/05/2023
#        - build-debian-x86_64-11-bullseye:
#            <<: *std-filters
## -------------------------------------
## UBUNTU OS  Frozen - 28/05/2023  DROP
## -------------------------------------
## KEEP needed for Raspbian OpenCPN v5.6
#        - build-ubuntu-armhf-1804-buster:
#            <<: *std-filters
##        - build-ubuntu-x86_64-1804-bionic:
##            <<: *std-filters
##        - build-ubuntu-x86_64-1804-bionic-gtk3:
##            <<: *std-filters
##        - build-ubuntu-armhf-2004-focal-gtk3:
##            <<: *std-filters
##        - build-ubuntu-x86_64-2004-focal-gtk3:
##            <<: *std-filters
orbs:
    cloudsmith: cloudsmith/cloudsmith@1.0.4
    win: circleci/windows@5.0

commands:
    deploy-code:
        parameters:
            install-python:
                type: boolean
                default: false
            DEPLOY-USE-ORB:
                type: boolean
                default: true
        steps:
            - when:
                condition: <<pipeline.parameters.run_workflow_deploy>>
                steps:
                - when:
                    condition: <<parameters.install-python>>
                    steps:
                    - run: sudo apt install -y python3-pip
                    - run: python3.8 -m pip install cloudsmith-cli
                - when:
                    condition: <<parameters.DEPLOY-USE-ORB>>
                    steps:
                    - cloudsmith/ensure-api-key
                    - cloudsmith/install-cli
                - run: bash ci/cloudsmith-upload.sh

    # if you want to use a local proxy add Acquire::http::Proxy \"http://192.168.1.1:3142\"; to a file called circleci-cache/apt-proxy. This will require
    #    --volume {your local directory}/circleci-cache:/home/circleci/circleci-cache
    # on the circleci local command line so that the docker image script can have access to the directory
    # if you are on a slow or data limited internet link you can put a copy of master.zip here, or allow one to be downloaded by the script, as it is used by the android builds to
    # provide the wxWidgets QT information.

##  --------------------
## OpenCPN 5.8 Plugins
## ---------------------
jobs:
    build-msvc-2022:
        executor:
            name: win/server-2022
            shell: cmd.exe
        environment:
        - OCPN_TARGET: MSVC
        - MSVC_VERSION: 2022
        - WX_VER: 31
        steps:
        - checkout
        - run:
            privileged: False
            shell: cmd.exe
            command: ci\circleci-build-msvc.bat
        - deploy-code:
            DEPLOY-USE-ORB: false
